#!/usr/bin/env python3
"""Generate Markdown comparison tables from the canonical Host Link JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "device-ranges" / "kv_device_ranges.json"
TABLE_DIR = ROOT / "tables"


def load_catalog() -> dict[str, Any]:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def cell(value: object) -> str:
    text = "-" if value is None else str(value)
    if text == "":
        text = "-"
    text = text.replace("|", "\\|")
    return text


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines)


def profile_table(payload: dict[str, Any]) -> str:
    rows: list[list[object]] = []
    for profile_id, profile in payload["profiles"].items():
        rows.append(
            [
                profile_id,
                profile["display_name"],
                profile["source_label"],
                profile["address_notation"],
                profile.get("base_profile", "-"),
                "Unconfirmed",
            ]
        )
    return "\n\n".join(
        [
            "# KEYENCE KV Host Link Profile Parameters",
            "<!-- Generated by tools/generate_profile_tables.py. Do not edit manually. -->",
            "Generated user-facing reference. Source: device-ranges/kv_device_ranges.json.",
            f"Schema {payload.get('schema_version', '-')}, date {payload.get('date', '-')}, scope {payload.get('scope', '-')}.",
            "## Purpose",
            "Profile parameters document canonical Host Link profile IDs, display names, source labels, and native or XYM notation relationships for user manuals and profile-selection tools.",
            "They do not prove that every address will be accepted by a connected PLC; use the PLC response and the application context for runtime truth.",
            "## Profile Summary",
            markdown_table(
                ["Profile ID", "Display name", "Source label", "Notation", "Base profile", "Verified models"],
                rows,
            ),
            "## Appendix: How To Read Cells",
            "- means no value applies to that profile.",
            "Unconfirmed means this catalog entry is adopted from existing profile data without a live-device verification record for that exact model.",
            "native means the profile uses the normal KEYENCE Host Link device notation. xym means the profile uses the XYM-compatible notation variant.",
            "",
        ]
    )


def range_table(payload: dict[str, Any]) -> str:
    profiles = list(payload["profiles"])
    headers = ["Device", "Device name", "Notation"] + profiles
    definition_rows: list[list[object]] = []
    rows: list[list[object]] = []
    for row in payload["device_range_rows"]:
        definition_rows.append([row["device_type"], row.get("device_name", "-"), row["notation"]])
        rows.append(
            [row["device_type"], row.get("device_name", "-"), row["notation"]]
            + [row["ranges"][profile] for profile in profiles]
        )
    return "\n\n".join(
        [
            "# KEYENCE KV Host Link Device Ranges",
            "<!-- Generated by tools/generate_profile_tables.py. Do not edit manually. -->",
            "Generated user-facing reference. Source: device-ranges/kv_device_ranges.json.",
            f"Schema {payload.get('schema_version', '-')}, date {payload.get('date', '-')}, scope {payload.get('scope', '-')}.",
            "## Purpose",
            "Device ranges compare the cataloged KEYENCE KV Host Link address ranges across canonical profiles.",
            "They are catalog data for profile selection, UI address pickers, diagnostics, and application-layer validation, not a production guarantee that every address can be read or written on a connected PLC.",
            "## Device Definitions",
            markdown_table(["Device", "Device name", "Notation"], definition_rows),
            "## Device Range Matrix",
            markdown_table(headers, rows),
            "## Appendix: How To Read Cells",
            "- means the device row is not available in that catalog profile.",
            "Range cells use the manual notation for the profile column. Native profiles show normal KEYENCE names such as R00000-R59915. XYM profiles show their compatible X/Y/M/L/D/E/F forms where the catalog defines them.",
            "decimal and hexadecimal describe the address notation family for that device row.",
            "",
        ]
    )


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            print(f"stale generated table: {path.relative_to(ROOT)}")
            return False
        print(f"fresh generated table: {path.relative_to(ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated tables are stale")
    args = parser.parse_args()

    payload = load_catalog()
    outputs = {
        TABLE_DIR / "kv_profile_parameters.md": profile_table(payload),
        TABLE_DIR / "kv_device_ranges.md": range_table(payload),
    }
    ok = all(write_or_check(path, content, args.check) for path, content in outputs.items())
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
